### PR TITLE
Dockerfile version of example commands

### PR DESCRIPTION
**Pull request by jkburges**

### CODE REVIEW

**Comment by treeder** [comment]
Thanks, I was avoiding making actual docker images for the development part of things since it just slows things down.

**Comment by jkburges** [comment]
Do you mean it slows down a developer using docker (as a development environment) or it would've slowed you down doing this example git project?

**Comment by treeder** [comment]
As a developer. Building an image to run/debug your program after every little change.

**Comment by jkburges** [comment]
I see.

**Pull request closed without merging**
